nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/xingzhang-suse/security-ui-exts/gh-pages/extensions/sbomscanner-ui-ext/0.5.0-rc2
  compressedEndpoint: >-
    https://raw.githubusercontent.com/xingzhang-suse/security-ui-exts/gh-pages/extensions/sbomscanner-ui-ext/0.5.0-rc2.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: SBOMScanner
    catalog.cattle.io/rancher-version: ">= 2.10.0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
